services:
  - type: web
    name: api-superheroe
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        value: mongodb+srv://gerardoavilesmoreno28:3eDtvChgOqfmrUNj@cluster0.mongodb.net/api-superheroes?retryWrites=true&w=majority 